services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8091:8080
      - 50000:50000
    container_name: midterm-jenkins
    volumes:
      - "/home/khunmeas/Code/DevOP/Midterm/file_jenkins:/var/jenkins_home"
    depends_on:
      - db
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: agent:latest
    container_name: agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDXjpQuBrfhf5jmhaCfNxdSysa/jXF8XOQIiaE+E+fUv khunmeas@khunmeas-Thin-GF63-12UCX"
    volumes:
      - "/home/khunmeas/Code/DevOP/Midterm/agent:/var/jenkins_home"

  db:
    image: postgres:16
    container_name: midterm-postgres
    user: root
    ports:
      - 5511:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
