spring.application.name=midtermdev

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5511/postgres
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
